version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - n 16
      - printenv
      - npm install env-cmd --legacy-peer-deps
      - npm install --legacy-peer-deps
  build:
    commands:
      - npm run build:staging
artifacts:
  files:
    - build**/*
  discard-paths: no
